version: '3.8'
services:
  web:
    build: .
    container_name: flask
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
